"""initial

Revision ID: 5d35d643b2c3
Revises: 
Create Date: 2024-06-20 18:40:37.993065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d35d643b2c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config__tg_channel',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_channel_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('datalake__tg_admin_log',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('datalake__tg_channel',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('datalake__tg_comment',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_post_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('datalake__tg_post',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_post_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('stat_post',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tg_post_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('views_1h', sa.Integer(), nullable=True),
    sa.Column('views_24h', sa.Integer(), nullable=True),
    sa.Column('total_reactions_count', sa.Integer(), nullable=True),
    sa.Column('reactions_1h', sa.Integer(), nullable=True),
    sa.Column('reaction_24h', sa.Integer(), nullable=True),
    sa.Column('comments_messages_count', sa.Integer(), nullable=True),
    sa.Column('comments_users_count', sa.Integer(), nullable=True),
    sa.Column('comments_channels_count', sa.Integer(), nullable=True),
    sa.Column('comments_messages_count_1h', sa.Integer(), nullable=True),
    sa.Column('comments_messages_count_24h', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('media', sa.String(length=255), nullable=True),
    sa.Column('forwards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('stat_reaction',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tg_post_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=True),
    sa.Column('reaction_emoticon', sa.String(length=255), nullable=True),
    sa.Column('reaction_emoticon_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('stat_user',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('scam', sa.Boolean(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_joined_by_link', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('config__tg_bot_session_pool',
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('api_id', sa.String(length=255), nullable=True),
    sa.Column('api_hash', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('session_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('config__tg_channel', sa.BigInteger(), nullable=True),
    sa.Column('config__tg_channel_pk', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['config__tg_channel'], ['config__tg_channel.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config__tg_bot_session_pool')
    op.drop_table('stat_user')
    op.drop_table('stat_reaction')
    op.drop_table('stat_post')
    op.drop_table('datalake__tg_post')
    op.drop_table('datalake__tg_comment')
    op.drop_table('datalake__tg_channel')
    op.drop_table('datalake__tg_admin_log')
    op.drop_table('config__tg_channel')
    # ### end Alembic commands ###
