"""essage=fix_string_len

Revision ID: 8f781162ba34
Revises: bfc9b4f49629
Create Date: 2024-06-26 02:49:33.044440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f781162ba34'
down_revision: Union[str, None] = 'bfc9b4f49629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('config__tg_bot_session_pool', 'phone_number',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('config__tg_bot_session_pool', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.add_column('stat_post', sa.Column('reactions_24h', sa.Integer(), nullable=True))
    op.alter_column('stat_post', 'message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('stat_post', 'link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('stat_post', 'media',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('stat_post', 'reaction_24h')
    op.alter_column('stat_reaction', 'reaction_emoticon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('stat_user', 'phone',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stat_user', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('stat_reaction', 'reaction_emoticon',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('stat_post', sa.Column('reaction_24h', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('stat_post', 'media',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('stat_post', 'link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('stat_post', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('stat_post', 'reactions_24h')
    op.alter_column('config__tg_bot_session_pool', 'status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('config__tg_bot_session_pool', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
